[package]
name = "mana"
version = "0.0.1"
authors = ["Tom Bazarnik <tommywalkie@gmail.com>"]
edition = "2018"
license = "MIT"
description = "Something something work-in-progress"
repository = "https://github.com/tommywalkie/mana.git"

[dependencies]
