name: macos

on: [push, pull_request]

jobs:
  rust:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest]
        rust: [stable, nightly, beta]
    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust }}
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: apple-${{ matrix.rust }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Test
      run: cargo test